# MyBatis-Plus ?????????

# ?????
generator.parent.package=lu.smartledger
entity.package=model.domain
controller.package=controller

# ?????
generator.jdbc.url=jdbc:mysql://127.0.0.1:3306/smartledger?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
generator.jdbc.username=root
generator.jdbc.password=1128lxlLXL@
generator.jdbc.driverClass=com.mysql.cj.jdbc.Driver

# ????
author=SmartLedger Team

# ????
generator.file.override=true
